# Generated by Django 4.2.7 on 2025-12-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_herosection_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
