# Generated by Django 4.2.7 on 2025-12-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_add_student_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('student_class', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stu_image/')),
            ],
        ),
        migrations.DeleteModel(
            name='Add_Student',
        ),
    ]
