# Generated by Django 4.2.7 on 2025-12-07 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_school_class_student_alter_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_class',
            name='student',
        ),
        migrations.AddField(
            model_name='school_class',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
